config/routes.rb
Rails.application.routes.draw do
  
   # deviseを使用するmodelの作成にて
  # いちよう記入した
  root to: 'homes#top'
  
  get 'home/about' => 'homes#about'

  
  devise_for :users
  
  # controllerファイルの作成
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update]
  
  
  # get 'users/show'
  # get 'users/edit'
  # get 'users/index'
  # 上記3つをまとめたのが↓
  resources :users, only:[:index, :show, :edit, :update]
  
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # Book用のmodelファイルの作成にて
  has_one_attached :image
  # modelファイルにアソシエーションの記載
  belongs_to :user
  
  # バリテーションの実装＞新規投稿が失敗したとき
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
  # modelファイルにアソシエーションの記載
  has_many :books, dependent:  :destroy
  
  # bookのindexページの左側の作成(User info)
  # Userモデルにnameとintroductionに加えて画像を扱うためのimageカラムが追記されたかのように扱うことができる
  has_one_attached :profile_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
  
  # バリテーションの実装＞ユーザーのプロフィール更新が失敗した時
  validates :name, presence: true
  # validates :introduction
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # バリテーションの実装＞新規投稿が失敗したとき
  before_action :authenticate_user!, except: [:top]
  
  # deviseを使用するviewの作成にて
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # sign upページの編集
  # アプリケーションを完成させよう2＞7章
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  # sign upページの編集
  # アプリケーションを完成させよう2＞7章
  def after_sign_out_path_for(resource)
    destroy_user_session_path
  end
  
  protected
# 認証　email
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  # アクセス制限の実装＞他人の投稿編集画面に遷移できない
  before_action :correct_user, only: [:edit, :update]
  
  def new
    # controllerファイルの作成
    @book = Book.all
  end

  def index
    # bookのindexページの右側の作成(Books)
    @books = Book.all
    @book = Book.new
  end

  def show
    
  end

  def edit
    # bookのeditページの作成
    @book = Book.find(params[:id])
    @book.delate
    redirect_to Book.index
  end
  
  def create
   @book = Book.new(book_params)
   @book.user_id = current_user.id
   if @book.save
    # フラッシュメッセージの実装＞新規投稿が成功したとき
    flash[:notice] = "successfully"
    redirect_to book_path(@book.id)
   else
     @books = Book.all
     flash[:alret] = "error"
     render :index
     
   end
  end
  
  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.save
      # フラッシュメッセージの実装>投稿の更新が成功したとき
      flash[:notice] = "successfully"
     redirect_to book_path(book.id)
    else
     flash[:alret] = "error"
     render :new
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
    def correct_user
      @book = Book.find(params[:id])
      @user = @book.user
      redirect_to(books_path) unless @user == current_user
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # アクセス制限の実装＞他人のユーザ情報編集画面に遷移できない
  # before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @user = User.find(params[:id])
  end
  
  
  def show
    # controllerファイルの作成2
    # より詳しくはアプリケーションを完成させよう2＞15章
    @user = User.find(params[:id])
    @users = @user.books
  end

  def edit
    # bookのindexページの左側の作成(User info)
    # からのuserのeditページの作成
    @user = User.find(params[:id])
  end
  
  # userのupdate機能の作成
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
     redirect_to user_path(user.id)
    else
     render :edit
    end
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)  
  end
  
  # アクセス制限の実装＞他人のユーザ情報編集画面に遷移できない
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<!--User info画面-->
<!--部分テンプレートになるファイル-->
<!--/users/何かしらのid にアクセスされたとき、このファイルが表示されるのか？-->
<h2>User info(app/views/books/_list.html.erb)</h2>
          <!--プロフィール画像-->
          <%= image_tag @user.get_profile_image %>
          <table class="table table-striped">
            <tbody>
              <!--name-->
              <h3><%= user.name %></h3>
              <!--introduction-->
              <h3><%= user.introduction %></h3>
            </tbody>
          </table>
          <% if user == current_user %>
          <p><%= link_to "プロフィール編集", edit_user_path(user) %></p>
          <% end %>
          
          
          <!--投稿データの新規投稿画面-->
          <h2 class="mt-3">New book</h2>
          <!-- form_with部分 -->
          <%= form_with model: book do |f| %>
          <h4>本のタイトル</h4>
          <%= f.text_field :title %>

          <h4>感想</h4>
          <%= f.text_area :body %>

          <%= f.submit 'Create Book',  class: "btn btn-secondary" %>
          <% end %>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

<h2>Book編集</h2>

<!--バリテーションの実装＞投稿の更新が失敗した時-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <label for="Title">Title</label>
  <%= f.text_field :title, autofocus: true, id:"Title", placeholder:"本のタイトル" %>
  <label for="Body">Body</label>
  <%= f.file_field :body, autofocus: true, id:"Body", placeholder:"感想" %>
  <%= f.submit "変更を保存" %>
<% end %>

<!--showとbackのリンク-->

app/views/books/index.html.erb
<!--bookのindexページの左側の作成(User info)-->
<!--(app/views/books/index.html.erb)-->

<main>
 <!--<p>サクセスメッセージorエラーメッセージの表示</p>-->
 <!--バリテーションの実装＞新規投稿が失敗したとき-->
 <% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <!--<div class="container px-5 px-sm-0">-->
   <div class="row">
    <div class="col-md-3">
          
          <!--部分テンプレート-->
          <%= render 'list', books: @books,user: current_user, book: @book %>
          
    </div>
    
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
      <% @books.each do |book| %>
      
      <p>Title</p>
      <span><%= book.title %></span>

      <p>Opinion</p>
      <span><%= book.body %></span>

      <% end %>
    </div>
   </div>
  <!--</div>-->
</main>

app/views/books/show.html.erb
<h1>Books#show_詳細画面</h1>
<p>Find me in app/views/books/show.html.erb</p>

  <!--アプリケーションを完成させよう2＞13章-->
  <% if @book.user == current_user %>
    <%= link_to "destroy", book_path(@book), method: :delete %>
  <% end %>
  
  <p><%= link_to "book編集", edit_book_path(@book.id) %></p>
  <%= link_to "Book削除", destroy_book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

app/views/homes/about.html.erb
<!--/home/aboutにアクセスされたとき、このファイルが表示されるはず-->
<!--<h1>app/views/homes/about.html.erbファイル</h1>-->

<!--welcome to Bookersと、フッターにCopyRight Infratop.incって書いてあるページが表示されるはず-->

<body>
  <main>
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">
          Welcome to <a>Bookers</a>!
        </h1>
      </div>
    </div>
  </main>
</body>

app/views/homes/top.html.erb
<main>
  
  <p id="notice"></p>
  
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
       <h1>welcome to Bookers !!(app/views/homes/top.html.erb)</h1>

       <p>in Bookers</p>

       <p>you can share and exchange your opinions , inpressions , and emotions</p>

       <p>about various books!</p>
       
       <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
         <div class="row">
          <%= link_to "Log in", new_user_session_path %>
         </div>
         
         <div class="row">
          <%= link_to "Sign Up", new_user_registration_path %>
         </div>
         
       </div>
       
      </div>
    </div>
  </div>
  
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Bootstrapを使うために必要な記述を追加する-->
    <!--linkをpackに変更-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     
    <!--ログイン済みの時-->
    <% if user_signed_in? %>
      <!--Bookersリンクを押すと、app/views/homes/top.htmi.erbファイルにパスしてほしい-->
       <a><%= link_to "Bookers", root_path %></a>
    
      <!--Homeリンクを押すと、app/views/users/show.html.erbファイルにパスしてほしい-->
      <li><%= link_to "Home", users_path %></li>
      <!--Usersリンクを押すと、app/views/books/index.html.erbファイルにパスしてほしい-->
      <li><%= link_to "Users", books_path %></li>
      <!--Booksリンクを押すと、画面右側にBooksというタイトルの
      投稿データ一覧画面としてapp/views/books/index.html.erbファイル内を提示してほしい-->
      <li><%= link_to "Books", books_path %></li>
      
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      
      <!--ログアウト時-->
    <% else %>
    <!--Bookersリンクを押すと、app/views/homes/top.htmi.erbファイルにパスしてほしい-->
    <a><%= link_to "Bookers", root_path %></a>
    
      <!--Homeリンクを押すと、app/views/users/top.html.erbファイルにパスしてほしい-->
      <li>"Home"</li>
      <!--Aboutリンクを押すと、app/views/homes/about.html.erbファイルにパスしてほしい-->
      <li>"About"</li>
      <!--Sign Upリンクを押すと、app/views/devise/registrations/new.html.erbファイルにパスしてほしい-->
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
       <!--Log inリンクを押すと、app/views/devise/session/new.html.erbファイルにパスしてほしい-->
      <li><%= link_to "Log in", new_user_session_path %></li>
    <% end %>

   </header>
    <%= yield %>
    
    
<!--フラッシュメッセージの実装＞新規投稿が成功したとき-->
<div class="text-success">
  <%= flash[:notice] %>
</div>
<div class="text-danger">
  <%= flash[:alret] %>
</div>
    
   <footer>
     <div class="container mt-5">
      <div class="row">
       <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
       </div>
      </div>
      </div>
   </footer>
  </body>

</html>

app/views/users/edit.html.erb
<!--app/views/users/edit.html.erb-->
<!--User#edit-->
<!--bookのindexページの左側の作成(User info)-->


<!--<main>-->
<!--  <p id="notice"></p>-->
<!--  <div class="container">-->
<!--    <div class="row">-->
<!--      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">-->
        
        
          <!--部分テンプレ-->
          <%= render 'books/list', books: @books %>
        
        
<!--        <%= f.submit 'Update User' %>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</main>-->


<h2>プロフィール編集</h2>

<!--バリテーションの実装＞ユーザーのプロフィール更新が失敗した時-->
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/index.html.erb
<%= render 'books/list', books: @books %>


<h1>ユーザーの一覧？</h1>

<%= @users.each do |user| %>

  <span><%= image_tag @user.get_profile_image %></span>

  <p>name</p>
  <span><%= user.name %></span>
  
  
  
<% end %>

app/views/users/show.html.erb
<!--Bookers2のユーザーのプロフィール情報画面(表示のみ)-->
<!--/users/なんかのid　にアクセスされたとき、このファイルが表示されるはず-->
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<!--この下におそらく投稿データの新規投稿画面として-->
<!--app/views/books/new.html.erbファイルが添付されると思う-->

<!--さらにサイト画面上右側に、投稿データの一覧画面として-->
<!--app/views/books/index.html.erbファイルが添付されると思う-->

<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image %>
  
  <% if @user == current_user %>
  <p><%= link_to "プロフィール編集", edit_user_path(@user.id) %></p>
  <% end %>
  
</div>